[build]
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["json5"]
  included_files = ["node_modules/json5/**"]

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  framework = "create-react-app"

[[headers]]
  for = "/kc-daily-news-editor"
  [headers.values]
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow, noarchive"
