export const newsSlots = [
  
{
  slotId: "1",
  sourceLabel: "RacingNews365",
  title: "Toto Wolff warns against F1 adopting “political mess” rules solution",
  summary: "Toto Wolff has warned Formula 1 against adopting Balance of Performance, arguing that it would create political problems and damage the competitive identity of the sport.",
  kcsQuickShift: "Wolff is fine with protection mechanisms for struggling power units, but he clearly does not want F1 turning into a BoP debate.",
  url: "https://racingnews365.com/toto-wolff-warns-against-f1-adopting-political-mess-rules-solution",
  imagePath: "/img/news/xpb/Mercedes/news-xpbtoto.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 23, 2026",
},
{
  slotId: "2",
  sourceLabel: "RacingNews365",
  title: "FIA announce tweaks to F1 rules as new regulations confirmed",
  summary: "The FIA World Motor Sport Council has approved several Formula 1 rule updates, including 2026 safety changes and the first issue of the 2027 technical regulations.",
  kcsQuickShift: "The biggest takeaway is that F1 is still adjusting the 2026 rules while already trying to clean up the path toward 2027.",
  url: "https://racingnews365.com/fia-announce-tweaks-to-f1-rules-as-new-regulations-confirmed",
  imagePath: "/img/news/kcai/news-FIA.jpg",
  photoCredit: "KC AI GENERATED IMAGE",
  dateLabel: "June 23, 2026",
},
{
  slotId: "3",
  sourceLabel: "RacingNews365",
  title: "Why Max Verstappen is always a threat on Red Bull home territory",
  summary: "Max Verstappen heads to the Red Bull Ring with a strong record at the circuit, where braking, traction and short-lap precision have often played to his strengths.",
  kcsQuickShift: "Red Bull may not have the clear fastest car, but Austria is exactly the type of circuit where Verstappen can still turn a weekend into a fight.",
  url: "https://racingnews365.com/why-max-verstappen-is-always-a-threat-on-red-bull-home-territory",
  imagePath: "/img/news/xpb/RedBull/xpbverstappen.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 23, 2026",
},
{
  slotId: "4",
  sourceLabel: "PlanetF1",
  title: "Aston Martin “rocketship” warning from Montoya amid Alonso to Alpine rumours",
  summary: "Juan Pablo Montoya has warned Fernando Alonso against leaving Aston Martin for Alpine, suggesting Alonso could regret it if Adrian Newey’s influence helps transform Aston Martin’s car.",
  kcsQuickShift: "Alonso’s future is getting interesting, but leaving before Aston Martin’s Newey project fully arrives would be a serious gamble.",
  url: "https://www.planetf1.com/news/aston-martin-rocketship-juan-pablo-montoya-fernando-alonso-alpine",
  imagePath: "/img/news/xpb/Aston/news-xpbfernando.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 23, 2026",
},
{
  slotId: "5",
  sourceLabel: "PlanetF1",
  title: "Lewis Hamilton “clear team leader” as Brundle issues Leclerc warning",
  summary: "Martin Brundle believes Lewis Hamilton is now looking like Ferrari’s clear team leader after his recent run of results, putting pressure on Charles Leclerc to respond strongly.",
  kcsQuickShift: "Hamilton’s Barcelona win has changed the tone at Ferrari, and Leclerc now needs Austria and Silverstone to steady the balance.",
  url: "https://www.planetf1.com/news/lewis-hamilton-ferrari-team-leader-martin-brundle-charles-leclerc",
  imagePath: "/img/news/Ferrari/news-ferrarilc.jpg",
  photoCredit: "Courtesy of Ferrari F1",
  dateLabel: "June 23, 2026",
},
{
  slotId: "6",
  sourceLabel: "Motorsport",
  title: "F1 revisits wet-weather boost mode as FIA ratifies rule changes",
  summary: "Formula 1 will partially restore Boost Mode in wet conditions for safety reasons, while the FIA has also ratified wider regulation changes for 2027 and beyond.",
  kcsQuickShift: "The boost-mode change is not about giving drivers more power in the wet — it is about reducing sudden power drops and improving safety.",
  url: "https://www.motorsport.com/f1/news/f1-revisits-wet-weather-boost-mode-as-fia-ratifies-rule-changes/10832642/",
  imagePath: "/img/news/kcai/news-tiresmiami.jpg",
  photoCredit: "KC AI GENERATED IMAGE",
  dateLabel: "June 23, 2026",
},
{
  slotId: "7",
  sourceLabel: "Formula1.com",
  title: "Norris says Hamilton can stick “middle finger up” to doubters after Barcelona win",
  summary: "Lando Norris says Lewis Hamilton’s first Ferrari victory at Barcelona gives him a strong answer to critics after a difficult first season in red.",
  kcsQuickShift: "Hamilton’s Ferrari win has clearly shifted the conversation, and even Norris sounds pleased to see him silence the doubters.",
  url: "https://www.formula1.com/en/latest/article/norris-says-hamilton-can-stick-middle-finger-up-to-doubters-after-barcelona-win.XeifoqmyClfEeQy2dncmJ",
  imagePath: "/img/news/xpb/Mclaren/news-xpblando.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},
{
  slotId: "8",
  sourceLabel: "Read Motorsport",
  title: "Why the Austrian Grand Prix could expose F1’s first true three-team fight of 2026",
  summary: "The Austrian Grand Prix could give F1 a clearer read on whether McLaren, Red Bull and Ferrari are all genuinely in the lead fight at the same time.",
  kcsQuickShift: "Austria’s short lap and heavy braking zones should make it harder for teams to hide their real pace.",
  url: "https://readmotorsport.com/2026/06/23/austrian-grand-prix-f1-three-team-fight-mclaren-red-bull-ferrari/",
  imagePath: "/img/news/raceposter/austriangrandprix.jpg",
  photoCredit: "KC AI GENERATED IMAGE",
  dateLabel: "June 23, 2026",
},
{
  slotId: "9",
  sourceLabel: "GrandPrix247",
  title: "Some technical insights ahead of the 2026 Formula 1 Austrian Grand Prix",
  summary: "Williams has highlighted tyre management, braking demands, kerb usage, weather risk and power-unit performance as key technical factors for the Austrian Grand Prix weekend.",
  kcsQuickShift: "Austria may look simple on paper, but the short lap, braking zones and changing weather can make setup choices very unforgiving.",
  url: "https://www.grandprix247.com/formula-1-news/some-technical-insights-ahead-of-the-2026-formula-1-austrian-grand-prix",
  imagePath: "/img/news/shut/williams/news-shutterstockalexcar.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "June 23, 2026",
},
{
  slotId: "10",
  sourceLabel: "Marca",
  title: "“Max no se guarda nada porque sabe lo fuerte que es” / “Max does not hold anything back because he knows how strong he is”",
  summary: "Marca looks at Max Verstappen’s confidence and strength heading into the Austrian Grand Prix, with the Red Bull Ring again putting the spotlight on the reigning champion. / Marca analiza la confianza y la fortaleza de Max Verstappen antes del Gran Premio de Austria, con el Red Bull Ring volviendo a poner el foco sobre el campeón.",
  kcsQuickShift: "Verstappen at Austria is always a headline, especially when Red Bull needs a home-race response. / Verstappen en Austria siempre es una historia importante, especialmente cuando Red Bull necesita responder en casa.",
  url: "https://www.marca.com/motor/formula1/gp-austria/2026/06/23/max-guarda-fuerte.html",
  imagePath: "/img/news/shut/RedBull/news-shutterstockredbull.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "June 23, 2026",
},


];
export default newsSlots;