export const newsSlots = [
  
{
  slotId: "1",
  sourceLabel: "ESPN",
  title: "Austrian Grand Prix 2026: Start Time, Schedule, How to Watch",
  summary: "ESPN breaks down the full Austrian Grand Prix weekend, including session times, viewing details and the key storylines heading into race week.",
  kcsQuickShift: "A useful race-week guide as F1 heads to Austria, where heat, strategy and the short Red Bull Ring layout could all play a major role.",
  url: "https://www.espn.co.uk/f1/story/_/id/49042004/austrian-grand-prix-2026-race-f1-start-s-how-watch-schedule-usa-tv-channel-live-stream-predictions-results",
  imagePath: "/img/news/raceposter/austriangrandprix.jpg",
  photoCredit: "KC AI",
  dateLabel: "June 22, 2026",
},
{
  slotId: "2",
  sourceLabel: "RacingNews365",
  title: "Weather Warning Issued as Austrian GP Set for Brutal Conditions",
  summary: "The Austrian Grand Prix could become the hottest race of the season so far, with temperatures expected to climb above 30 degrees Celsius and possibly reach 35 degrees at the circuit.",
  kcsQuickShift: "This could become a major tyre, cooling and driver-management weekend, especially if the heat stays locked in through race day.",
  url: "https://racingnews365.com/weather-warning-issued-as-austrian-gp-set-for-brutal-conditions",
  imagePath: "/img/news/kcai/austriaweather.jpg",
  photoCredit: "KC AI",
  dateLabel: "June 22, 2026",
},
{
  slotId: "3",
  sourceLabel: "RacingNews365 NL",
  title: "Verstappen Keert Terug Naar Zeer Succesvolle F1-Grond / Verstappen Returns to Very Successful F1 Ground",
  summary: "Max Verstappen keert terug naar Oostenrijk, een circuit waar hij in het verleden veel succes heeft gehad. / Max Verstappen heads back to Austria, a venue that has been one of his most successful hunting grounds in Formula 1.",
  kcsQuickShift: "Austria is always a major Verstappen weekend, and Red Bull will want its home race to become a turning point. / Oostenrijk is altijd een belangrijk Verstappen-weekend, en Red Bull zal hopen dat de thuisrace een kantelpunt wordt.",
  url: "https://racingnews365.nl/verstappen-keert-terug-naar-zeer-succesvolle-f1-grond",
  imagePath: "/img/news/xpb/RedBull/xpbmaxspain2.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},
{
  slotId: "4",
  sourceLabel: "Crash.net",
  title: "Can McLaren Challenge Mercedes and Ferrari in Austria?",
  summary: "Andrea Stella has assessed McLaren’s Austrian Grand Prix chances after the team slipped behind Mercedes and Ferrari in recent races, with Austria expected to test braking stability, tyre use and upgrade progress.",
  kcsQuickShift: "McLaren may not be the favourite in Austria, but the Red Bull Ring gives them a different type of test than Barcelona.",
  url: "https://www.crash.net/f1/news/1099037/1/can-mclaren-challenge-mercedes-and-ferrari-f1-boss-predicts-austrian-gp-chances",
  imagePath: "/img/news/xpb/Mclaren/news-xpblandomonaco.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},
{
  slotId: "5",
  sourceLabel: "ESPN",
  title: "Lewis Hamilton, Fred Vasseur and Ferrari’s F1 Turnaround",
  summary: "ESPN looks at how Lewis Hamilton and Fred Vasseur have helped reshape Ferrari’s approach, with Hamilton’s Barcelona win adding weight to the idea that Ferrari’s 2026 evolution is starting to work.",
  kcsQuickShift: "Ferrari now arrives in Austria with momentum, and Hamilton’s role inside the team is becoming one of the biggest stories of the season.",
  url: "https://www.espn.co.uk/f1/story/_/id/49117384/lewis-hamilton-fred-vasseur-ferrari-evolution-secret-f1-turnaround",
  imagePath: "/img/news/Ferrari/Lewis/news-lewisandcharlesmontreal.jpg",
  photoCredit: "Courtesy of Ferrari F1",
  dateLabel: "June 22, 2026",
},
{
  slotId: "6",
  sourceLabel: "RacingNews365",
  title: "Carlos Sainz Reveals Surprising Positive to Williams Woes",
  summary: "Carlos Sainz says Williams’ difficult start to 2026 tested his faith, but also forced changes inside the team that may help the project long term.",
  kcsQuickShift: "Williams is still under pressure, but Sainz seems to believe the early-season pain has exposed problems that needed fixing.",
  url: "https://racingnews365.com/carlos-sainz-reveals-surprising-positive-to-williams-woes-after-test-of-faith",
  imagePath: "/img/news/xpb/Williams/xpbcarlosspain.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},
{
  slotId: "7",
  sourceLabel: "RacingNews365 NL",
  title: "Audi Komt Met Uniek Alternatief Voor Belangrijke Nieuwe FIA-Regeling / Audi Proposes Unique Alternative to Major FIA Rule",
  summary: "Audi heeft een alternatief idee voorgesteld rond de nieuwe FIA-regels, met Mattia Binotto die zoekt naar een eerlijkere manier om achterblijvende fabrikanten dichter bij de top te brengen. / Audi has proposed an alternative approach to the FIA’s new rules, with Mattia Binotto looking for a fairer way to help manufacturers close performance gaps.",
  kcsQuickShift: "Audi clearly wants the engine rules cleaned up before the gap becomes too political. / Audi wil duidelijk dat de motorregels worden aangescherpt voordat het verschil te politiek wordt.",
  url: "https://racingnews365.nl/audi-komt-met-uniek-alternatief-voor-belangrijke-nieuwe-fia-regeling",
  imagePath: "/img/news/shut/Audi/news-audibinitto.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "June 22, 2026",
},
{
  slotId: "8",
  sourceLabel: "The Race",
  title: "F1 Engine Games Have Immediately Become Absurd",
  summary: "The Race argues that F1’s additional engine development system is already creating political gamesmanship, with manufacturers pushed into awkward arguments over who has fallen furthest behind.",
  kcsQuickShift: "This is exactly the kind of regulation issue that can become bigger than the racing if the FIA does not get it under control.",
  url: "https://www.the-race.com/formula-1/aduo-engine-games-make-a-mockery-of-f1/",
  imagePath: "/img/news/shut/Races/news-shutterstockmiamipit.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "June 22, 2026",
},
{
  slotId: "9",
  sourceLabel: "Motorsport.com",
  title: "Isack Hadjar Reveals What His Relationship With Max Verstappen Is Like",
  summary: "Isack Hadjar has opened up about life alongside Max Verstappen, giving insight into the working relationship between Red Bull’s established benchmark and one of F1’s rising names.",
  kcsQuickShift: "Hadjar’s comments matter because every Red Bull teammate relationship is measured against the Verstappen standard.",
  url: "https://www.motorsport.com/f1/news/isack-hadjar-reveals-what-his-team-mate-relationship-with-max-verstappen-is-like/10832369/",
  imagePath: "/img/news/xpb/RedBull/news-xpbisack.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},
{
  slotId: "10",
  sourceLabel: "Motorsport.com",
  title: "The Adrian Newey Quality That Keeps Aston Martin Believing",
  summary: "Aston Martin’s poor start to 2026 has not shaken the team’s belief in Adrian Newey, with Pedro de la Rosa pointing to Newey’s long-term ability to solve problems and build performance.",
  kcsQuickShift: "Aston Martin is struggling badly now, but Newey’s reputation is why the team is not ready to panic yet.",
  url: "https://www.motorsport.com/f1/news/the-adrian-newey-quality-that-keeps-aston-martin-believing/10831909/",
  imagePath: "/img/news/xpb/Aston/news-xpbneweystroll.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "June 22, 2026",
},


];
export default newsSlots;