export const newsSlots = [
  {
  slotId: 1,
  sourceLabel: "ESPN",
  title: "Zak Brown Says He Would Welcome Christian Horner Back To F1",
  summary: "Zak Brown says he would welcome Christian Horner back into Formula 1 despite their rocky past. Horner has been linked with a possible return through Alpine, while Brown also used the issue to repeat his concern that F1 must avoid more multi-team ownership links that could hurt sporting fairness.",
  kcsQuickShift: "This is classic F1 politics because Brown can respect Horner’s record and still push hard against team ownership links that he thinks are bad for the sport.",
  url: "https://www.espn.co.uk/f1/story/_/id/48568268/zak-brown-welcome-christian-horner-back-f1-rocky-relationship",
  imagePath: "/img/news/shut/news-shutterstockbrown.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "Apr. 23, 2026",
},

{
  slotId: 2,
  sourceLabel: "RacingNews365.nl",
  title: "Montoya roept op tot Verstappen-verbod: \"Hij kan zijn been breken!\" EN: Montoya Calls For Verstappen Ban: \"He Could Break His Leg!\"",
  summary: "Juan Pablo Montoya vindt dat Red Bull Max Verstappen moet verbieden om nog op de Nordschleife te rijden na het dodelijke ongeluk met Juha Miettinen. Montoya zegt dat Red Bull Verstappen moet beschermen, omdat een blessure aan zijn been of arm enorme gevolgen zou hebben voor de investering die het team in hem heeft gedaan. EN: Juan Pablo Montoya believes Red Bull should ban Max Verstappen from driving on the Nordschleife after the fatal accident involving Juha Miettinen. Montoya says Red Bull should protect Verstappen because an injury to his leg or arm could have major consequences for the investment the team has made in him.",
  kcsQuickShift: "Montoya is looking at this from a team protection angle, but telling Verstappen what he can and cannot drive is never going to be a simple conversation. NL: Montoya bekijkt dit vanuit teambescherming, maar Verstappen vertellen waarin hij wel en niet mag rijden wordt nooit een makkelijk gesprek.",
  url: "https://racingnews365.nl/montoya-roept-op-tot-verstappen-verbod-hij-kan-zijn-been-breken",
  imagePath: "/img/news/shut/news-shutterstockmax.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 3,
  sourceLabel: "RacingNews365",
  title: "Red Bull urged to consider Max Verstappen ban",
  summary: "Red Bull have been urged to consider banning Max Verstappen from competing outside of Formula 1 following a fatal accident at the Nürburgring Nordschleife. Juan Pablo Montoya believes the risk of injury is too high and says the team must protect its investment in Verstappen, warning that even a leg or arm injury could have major consequences.",
  kcsQuickShift: "This is really about risk versus freedom because Verstappen loves racing anything, but Red Bull has a massive investment to protect if something goes wrong.",
  url: "https://racingnews365.com/red-bull-urged-to-consider-max-verstappen-ban",
  imagePath: "/img/news/kcai/news-GP3max.jpg",
  photoCredit: "KCAI",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 4,
  sourceLabel: "RacingNews365",
  title: "Lando Norris spies McLaren advantage in Mercedes battle",
  summary: "Lando Norris believes McLaren has a potential advantage over Mercedes in their current battle despite Mercedes’ strong start to the 2026 season. Norris pointed to areas where McLaren’s car performance and race pace could still challenge, even as Mercedes holds the early upper hand in results and consistency.",
  kcsQuickShift: "This feels like Norris seeing a window because Mercedes looks strong right now, but McLaren clearly thinks they are not far off once everything clicks.",
  url: "https://racingnews365.com/lando-norris-spies-mclaren-advantage-in-mercedes-battle",
  imagePath: "/img/news/shut/news-shutterstockmclarenpit.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 5,
  sourceLabel: "Crash.net",
  title: "McLaren addresses 'total nonsense' Gianpiero Lambiase F1 team boss rumours",
  summary: "McLaren have dismissed suggestions that Gianpiero Lambiase is being lined up as a future team principal, calling the rumours 'total nonsense'. The team made it clear that Lambiase will join as Chief Racing Officer and support Andrea Stella, not replace him, shutting down speculation about a leadership change.",
  kcsQuickShift: "This one needed shutting down because the rumours were getting out of control, and McLaren is making it clear Stella is not going anywhere.",
  url: "https://www.crash.net/f1/news/1093336/1/mclaren-addresses-total-nonsense-gianpiero-lambiase-f1-team-boss-rumours",
  imagePath: "/img/news/shut/news-shutterstockstella.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 6,
  sourceLabel: "M4 Sport",
  title: "Piastri a szabálymódosításokról: \"Remélem, kicsit visszakanyarodunk a normalitáshoz\" EN: Piastri on rule changes: \"I hope we return a bit to normality\"",
  summary: "Oscar Piastri szerint a 2026-os szabályok módosításai jó irányba tett lépések lehetnek, különösen a túlzott energiamenedzsment és a kiszámíthatatlan viselkedés csökkentésében. Úgy érzi, az első futamokon látott problémák után ezek a változtatások segíthetnek visszahozni egy természetesebb, jobban vezethető autót. EN: Oscar Piastri believes the 2026 rule tweaks are a step in the right direction, particularly in reducing excessive energy management and unpredictable car behaviour. After the issues seen in the opening races, he hopes the changes will bring the cars back to a more natural and driveable state.",
  kcsQuickShift: "Piastri is basically saying what a lot of drivers are thinking, these cars got too complicated and now F1 is trying to bring things back under control. HU: Piastri lényegében azt mondja, amit sok pilóta gondol, ezek az autók túl bonyolultak lettek, és most próbálják visszahozni az egyensúlyt.",
  url: "https://m4sport.hu/forma-1/f1-hirek/cikk/2026/04/24/piastri-a-szabalymodositasokrol-remelem-kicsit-visszakanyarodunk-a-normalitashoz",
  imagePath: "/img/news/shut/news-shutterstockoscar.jpg",
  photoCredit: "Shutterstock",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 7,
  sourceLabel: "FormulaPassion",
  title: "Mansell: \"Vorrei vedere più potere decisionale nei piloti invece che nei computer\" EN: Mansell: \"I would like to see more decision-making power in the drivers rather than computers\"",
  summary: "Nigel Mansell ritiene che la Formula 1 moderna abbia tolto troppo controllo ai piloti, con un eccessivo affidamento su sistemi elettronici e gestione computerizzata. Secondo l'ex campione del mondo, le decisioni chiave dovrebbero tornare maggiormente nelle mani dei piloti per rendere le corse più autentiche e legate all’abilità umana. EN: Nigel Mansell believes modern Formula 1 has taken too much control away from drivers due to heavy reliance on electronics and computer management. The former world champion argues key decisions should return more to the drivers to make racing feel more authentic and based on human skill.",
  kcsQuickShift: "Mansell is basically calling out what a lot of fans feel, too much is controlled by systems now and not enough by the driver in the cockpit. IT: Mansell dice quello che molti tifosi pensano, oggi decide troppo il sistema e troppo poco il pilota.",
  url: "https://www.formulapassion.it/f1/f1-news/mansell-vorrei-vedere-piu-potere-decisionale-nei-piloti-invece-che-computer",
  imagePath: "/img/news/xpb/news-xpb4.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "Apr. 24, 2026",
},

{
  slotId: 8,
  sourceLabel: "RacingNews365",
  title: "Audi announce Le Mans legend to senior new F1 position",
  summary: "Audi have appointed three-time Le Mans winner Allan McNish as Racing Director in a newly created role to support their Formula 1 project. The move follows the departure of Jonathan Wheatley, with McNish set to work alongside Mattia Binotto and focus on improving trackside operations and overall performance as Audi builds toward long-term success.",
  kcsQuickShift: "This is a smart move because Audi needs stability right now and bringing in someone who knows the brand inside out helps steady the whole project.",
  url: "https://racingnews365.com/audi-announce-le-mans-legend-to-senior-new-f1-position",
  imagePath: "/img/news/xpb/news-xpbaudigabby.jpg",
  photoCredit: "XPB IMAGES",
  dateLabel: "Apr. 24, 2026",
},
  {
    slotId: 9,
    sourceLabel: "M4 Sport",
    title: "Félig új autót tesztelt a Ferrari Monzában, a Red Bull-lal Verstappen tért vissza Silverstone-ban EN:Ferrari tested a half-new car at Monza while Verstappen returned with Red Bull at Silverstone",
    summary: "A Ferrari egy jelentősen frissített autót tesztelt Monzában egy forgatási nap során, több új elemmel a teljesítmény javítása érdekében. Eközben a Red Bull Silverstone-ban futott tesztet, ahol Max Verstappen is pályára lépett adatgyűjtés céljából. EN:Ferrari tested a heavily updated car at Monza during a filming day with multiple new components, while Red Bull also ran at Silverstone with Max Verstappen returning to gather data on recent developments.",
    kcsQuickShift: " This is all about upgrades now because teams are pushing hard before Miami. HU:Most minden a fejlesztésekről szól Miami előtt.",
    url: "https://m4sport.hu/forma-1/f1-hirek/cikk/2026/04/23/felig-uj-autot-tesztelt-a-ferrari-monzaban-a-red-bull-lal-verstappen-tert-vissza-silverstone-ban",
    imagePath: "/img/news/ferrari/news-ferrari6.jpg",
    photoCredit: "Courtesy of Ferrari F1",
    dateLabel: "April 23, 2026",
  },

  {
    slotId: 10,
    sourceLabel: "The Race",
    title: "F1 hints at major engine rules pivot for 2031",
    summary: "Formula 1 has begun early discussions about a potential shift in engine regulations for 2031, with interest in simplifying the current hybrid systems. Ideas include reducing complexity and costs while keeping sustainable fuels, signalling that F1 is already planning a longer-term rethink beyond the 2026 rules.",
    kcsQuickShift: " They are already thinking beyond 2026 which tells you this is a long game.",
    url: "https://www.the-race.com/formula-1/f1-hints-at-major-engine-rules-pivot-for-2031-wh/",
    imagePath: "/img/news/shut/news-shutterstockstefano.jpg",
    photoCredit: "Shutterstock",
    dateLabel: "April 23, 2026",
  }
];